// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFzWyZlGeUVcLgNI3eKNr5J6f4pp-4yi4',
    appId: '1:58943886099:web:8b01a3b33d8e35e68d80e6',
    messagingSenderId: '58943886099',
    projectId: 'smart-wearable-app-dae6c',
    authDomain: 'smart-wearable-app-dae6c.firebaseapp.com',
    storageBucket: 'smart-wearable-app-dae6c.firebasestorage.app',
    measurementId: 'G-G8NNQFHRY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyseMzbH5zu3DVo_dIR2PWVMh46vpN0JE',
    appId: '1:58943886099:android:0e34ed92a66e30428d80e6',
    messagingSenderId: '58943886099',
    projectId: 'smart-wearable-app-dae6c',
    storageBucket: 'smart-wearable-app-dae6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnLPypbOdcGUFwulmcoK8uIxfxo42t1Zw',
    appId: '1:58943886099:ios:821867f10506632b8d80e6',
    messagingSenderId: '58943886099',
    projectId: 'smart-wearable-app-dae6c',
    storageBucket: 'smart-wearable-app-dae6c.firebasestorage.app',
    iosBundleId: 'com.example.smartWearableApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnLPypbOdcGUFwulmcoK8uIxfxo42t1Zw',
    appId: '1:58943886099:ios:821867f10506632b8d80e6',
    messagingSenderId: '58943886099',
    projectId: 'smart-wearable-app-dae6c',
    storageBucket: 'smart-wearable-app-dae6c.firebasestorage.app',
    iosBundleId: 'com.example.smartWearableApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFzWyZlGeUVcLgNI3eKNr5J6f4pp-4yi4',
    appId: '1:58943886099:web:79466e53d8c88b3d8d80e6',
    messagingSenderId: '58943886099',
    projectId: 'smart-wearable-app-dae6c',
    authDomain: 'smart-wearable-app-dae6c.firebaseapp.com',
    storageBucket: 'smart-wearable-app-dae6c.firebasestorage.app',
    measurementId: 'G-P65QGQM5ME',
  );
}
